version: 2.1
workflows:
  test:
    jobs:
      - test_only

step_defs:
    - run: &node_version
          name: Set Node version
          command: |
              nvm install v16
              nvm alias default v16
              echo "nvm use default" >> $BASH_ENV
    - run: &check_version
          name: Check Node version
          command: node -v | grep v16

jobs:
  test_only:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: *node_version
      - run: *check_version
      - run:
          name: Install
          command: npm ci
      - run:
          name: Test
          command: npm test
